version: '3'
services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: bubba
    volumes:
      - db:/var/lib/postgresql/data
      -  ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
